[package]
name = "mapmachine"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
simple_logger = "2.1.0"
log = "0.4.14"
# gdal = "0.14.0"
gdal = { path = "../gdal-rs" }
png = "0.17.7"