version: "3.9"
services:
  minio:
    # We specify the version because some newer versions have issues with ETag headers on large
    # files that are uploaded in chunks
    image: minio/minio:RELEASE.2023-02-17T17-52-43Z
    entrypoint: sh
    command: -c 'mkdir -p /data/rasters && minio server --console-address ":9001" /data'
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"


volumes:
  minio_data:
